// Regenerates packages/ui/src/index.ts from the component folder tree.
// A component is any src/<Name>/<Name>.tsx. Hooks + primitives are re-exported wholesale.
import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, "..", "src");

const components = readdirSync(src, { withFileTypes: true })
  .filter((d) => d.isDirectory() && d.name !== "hooks" && d.name !== "primitives")
  .map((d) => d.name)
  .filter((name) => existsSync(join(src, name, `${name}.tsx`)))
  .sort((a, b) => a.localeCompare(b));

const lines = [
  "/**",
  " * `@balaur/ui` — the OCTANT design system as atomic React components, plus the",
  " * shared hooks and primitives they compose from. (Generated by scripts/gen-barrel.mjs.)",
  " *",
  ' * Import the token stylesheet once at your app/root:',
  ' *   import "@balaur/tokens/tokens.css";',
  " */",
  "",
  'export * from "./hooks";',
  'export * from "./primitives";',
  "",
  ...components.map((name) => `export * from "./${name}/${name}.tsx";`),
  "",
];

writeFileSync(join(src, "index.ts"), lines.join("\n"));
console.log(`barrel: ${components.length} components + hooks + primitives`);
